dist: bionic

language: cpp

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - sudo add-apt-repository -y ppa:edd/misc

install:
  - sudo apt-get install libboost-all-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - make clean all
  - make all -j 4
